config/routes.rb
MiniFb::Application.routes.draw do
  root 'home#index'
  
  devise_for :users

  resources :users, :only => [:show] do
    resources :follow, :only => [:create,:show,:destroy]
    resources :albums, :only => [:new,:create,:show,:destroy,:update,:index,:edit] do
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get,:post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :delete

  resources :albums
  

  devise_scope :user do
    match '/login', to: 'devise/sessions#new', via: 'get'
    match '/login', to: 'devise/sessions#create', via: 'post'
    match '/register', to: 'devise/registrations#new', via: 'get'
    match '/logout', to: 'devise/sessions#destroy', via: 'delete'
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user
	has_many :photos, :dependent => :destroy
	accepts_nested_attributes_for :photos, :allow_destroy => true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :album
	validates :name, presence: :true
	has_attached_file :pic
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  has_many :albums, :dependent => :destroy

  friendly_id :username, use: :slugged
  validates :username, presence: true
  validates :email, presence: true
  validates :location, presence: true
  has_attached_file :photo, :styles => { :small => "150x150>" }
  acts_as_followable
  acts_as_follower

  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image.png']

  

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.username = auth.info.name
  		user.location = auth.info.location
  		user.email = auth.info.email
  		user.slug = auth.info.name.parameterize
  		user.oauth_token = auth.credentials.token
  		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user1 = FbGraph::User.fetch(auth.info.name.split[0], :access_token => auth.credentials.token)
      albums = user1.albums
  		user.save(:validate => false)
  	end
  end

  #def should_generate_new_friendly_id?
  #  new_record?
  #end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def self.search(search)
  if search
    find(:all, :conditions => ['username LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		if @user == current_user
			@albums= Album.where("user_id = ? ",params[:user_id])
		elsif @user.following?(current_user) and current_user.following?(@user)
			@albums = Album.where("user_id = ? and privacy = ? or privacy = ?",params[:user_id],"Visible to Friends","Public")
		else
			@albums = Album.where("user_id = ? and privacy = ?",params[:user_id],"public")
		end
		if @user.oauth_token != nil
			@fbuser = FbGraph::User.me(@user.oauth_token)
      		@fbalbums = @fbuser.albums
      	end
	end

	def new
		@album = Album.new
		@album.photos.build unless @album.photos.present?
	end

	def create
		@album = Album.new(album_params)
		@album.user_id = current_user.id
		if @album.save
			redirect_to user_albums_path(current_user.id), :notice => "Album Created..!!"
		else
			render :action => "new"		
		end 
	end

	def show
		@user = User.find(params[:user_id])
		if @user.oauth_token != nil
			@fbuser = FbGraph::User.me(@user.oauth_token)
      		@fbalbums = @fbuser.albums
      		@album = @fbalbums.detect{|a| a.identifier == params[:id]}
      	else
      		@album = Album.find(params[:id])
		end

		@photos = @album.photos

	end

	def edit
		@album = Album.find(params[:id])
		@album.photos.build unless @album.photos.present?
	end

	def update
		@album = Album.find(params[:id])
		if @album.update_attributes(album_params)
			flash[:success] = "Album Updated"
			redirect_to user_album_path(current_user.id,@album)
		else
			render 'edit'
		end
	end

	def destroy
		if params[:photo_id]
			Photo.find(params[:photo_id]).destroy
			redirect_to user_album_path(params[:user_id],params[:id]) 
		else
			Album.find(params[:id]).destroy
			flash[:success] = "User deleted"
			redirect_to user_albums_path(params[:user_id]) 
		end
	end

	def album_params
    	params.require(:album).permit(:name, :privacy, :photos_attributes => [:name,:pic])
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :location, :email, :password, :password_confirmation, :photo)
    end

    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:username, :location, :email, :password, :password_confirmation, :photo)
    end

    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :location, :email, :password, :password_confirmation, :current_password, :photo)
    end
  end
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController

  def show
  	@user = User.find(params[:user_id])
  	if params[:info] == "following"
  		@follow = @user.all_following
  	elsif params[:info] == "followers"
  		@follow = @user.followers
  	end
  end

  def create
  	@user = User.find(params[:user_id])
  	current_user.follow(@user)
  	redirect_to user_path(@user)
  end

  def destroy
  	@user = User.find(params[:user_id])
  	current_user.stop_following(@user)
  	redirect_to user_path(@user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@user = User.paginate(page: params[:page], per_page: 12).search(params[:search])
	end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
	def new
		@user = User.new
	end   

	def create
		@user=User.new(user_params)
		if @user.save?
			sign_in @user
			flash[:success] = "Welcome to Mini fb"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find params[:id]

		if @user.update_attributes params[:user]
			flash[:notice] = 'The User is successfully updated!'
			redirect_to user_path
		else
			flash[:error] = @user.errors.full_messages[0]
			redirect_to edit_user_registration_path
		end
	end

	private
	
	def user_params
    	params.require(:user).permit(:name, :email, :location, :password, :password_confirmation)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include Devise::Controllers::Helpers
  def create
  	user = User.from_omniauth(env["omniauth.auth"])
  	session[:user_id] = user.id
  	sign_in user, :bypass => true
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find_by_slug(params[:id])
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<div class="col-lg-12 text-center v-center">
<h1>Edit Album</h1>
</div>

<div class="input-group" style="width:340px;margin:0 auto;">
	<%= form_for( @album, metod: :put, :html => { :multipart => true}) do |f| %>
		<p class="lead"> Album Name
		  <%= f.text_field :name, :autofocus => true, :class => "form-control input-lg" %>
		</p>
		<%= f.fields_for :photos, @album.photos.build do |p| %>
			<p class="lead"> Photo Name
		  		<%= p.text_field :name, :class => "form-control input-lg" %>
			</p>

			<p class="lead">
				<%= p.file_field :pic %>
			</p>
		<% end %>
		<p class="lead">
			<%= f.select :privacy, [["Public"], ["Private"], ["Visible to Friends"]] %>
		</p>
		<div class="col-lg-12 text-center v-center">
	    	<%= f.submit "Update", :class => "btn btn-lg btn-primary" %></div>
	  	</div>
	<% end %>
</div>

app/views/albums/index.html.erb
<center>
<h1>
	Albums
    <% if current_user == @user %>
        <%= link_to "New", new_user_album_path(@user), class: "btn btn-primary btn-lg" %>
    <% end %>
</h1>
<div class="container">
    <div class="row">
        <% @albums.each do |album| %>
            <div class="col-md-4">
             	<div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>
                            <%= link_to album.name, user_album_path(@user.id,album), {:style=>'color:#110022;'} %>
                        </h3>
                        <% if current_user == @user %>
                            <%= album.privacy %>
                        <% end %>
                    </div>
                    <div class="panel-body panelbodylead">
                        <% if album.photos.count != 0 %>
                            <%= image_tag album.photos.first.pic.url, :size => "150x150" %>
                            <% if album.photos.count > 1 %>
                                <%= image_tag album.photos.last.pic.url, :size => "150x150" %>
                            <% end %>
                        <% end %>
                	</div>
                    <% if current_user == @user %>
                        <%= link_to "Delete", user_album_path(@user.id,album), method: :delete, class: "btn btn-danger btn-lg" %>
                    <% end %>
                </div>
            </div>   
        <% end %>
        <% if @user.oauth_token != nil %>
            <div class="container">
                <div class="row">
                    <% @fbalbums.each do |fbalbum| %>
                        <div class="col-md-3">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3>
                                        <%= link_to fbalbum.name, user_album_path(@user,fbalbum.identifier), {:style=>'color:#110022;'} %>
                                    </h3>
                                </div>
                                <div class="panel-body panelbodylead">
                                    <% if fbalbum.photos.count != 0 %>
                                        <%= image_tag fbalbum.photos.first.source, :size => "150x150" %>
                                        <% if fbalbum.photos.count > 1 %>
                                            <%= image_tag fbalbum.photos.last.source, :size => "150x150" %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>   
                    <% end %>
                </div> 
            </div>
        <% end %>
    </div> 
</div>
</center>

app/views/albums/new.html.erb
<div class="col-lg-12 text-center v-center">
	<h1>Create New Album</h1>
</div>
<div class="input-group" style="width:340px;margin:0 auto;">
	<%= form_for( @album, metod: :post, :html => { :multipart => true}) do |f| %>
		<p class="lead"> Album Name
		  <%= f.text_field :name, :autofocus => true, :class => "form-control input-lg" %>
		</p>
		<%= f.fields_for :photos do |p| %>
			<p class="lead"> Photo Name
		  		<%= p.text_field :name, :class => "form-control input-lg" %>
			</p>

			<p class="lead">
				<%= p.file_field :pic %>
			</p>
		<% end %>
		<p class="lead">
			<%= f.select :privacy, [["Public"], ["Private"], ["Visible to Friends"]] %>
		</p>
		<div class="col-lg-12 text-center v-center">
	    	<%= f.submit "Create", :class => "btn btn-lg btn-primary" %></div>
	  	</div>
	<% end %>
</div>

app/views/albums/show.html.erb
<center>
<h1>
	<%= @album.name %>
	<% if @user.oauth_token == nil %>
		<%= link_to "Add Photo", edit_user_album_path(@user,@album), class: "btn btn-primary btn-lg" %>
	<% end %>
</h1>
<div class="container">
    <div class="row">
    	<% if @user.oauth_token == nil %>
	        <% @photos.each do |photo| %>
	            <div class="col-md-3">
	             	<div class="panel panel-default">
	                    <div class="panel-heading">
	                        <h3>
	                            <%= photo.name %>
	                        </h3>
	                    </div>
	                    <div class="panel-body panelbodylead">
	                        <%= image_tag photo.pic.url, :size => "150x150" %>
	                	</div>
	                	<% if current_user == @user %>
                        	<%= link_to "Delete", user_album_path(@user.id,@album, :photo_id => photo.id), method: :delete, class: "btn btn-danger btn-lg" %>
                   		<% end %>
	                </div>
	            </div>   
	        <% end %>
        <% else %>
        	<% @photos.each do |photo| %>
	            <div class="col-md-3">
	             	<div class="panel panel-default">
	                    <div class="panel-body panelbodylead">
	                        <%= image_tag photo.source, :size => "150x150" %>
	                	</div>
	                </div>
	            </div>   
	        <% end %>
        <% end %>
    </div> 
</div>
</center>

app/views/follow/show.html.erb
<div class="col-lg-12 text-center v-center">

	<% if params[:info] == "followers"%>
		<h1><font size="12">List of followers of <%= User.find(params[:user_id]).username %></font></h1>
	<% else %>
		<h1>
            <font size="12">
                List of followed users of <%= User.find(params[:user_id]).username %>
            </font>
        </h1>
	<% end %>
</div>
<div class="container"><hr>
    <div class="row">
        <% @follow.each do |follow| %>
        	<div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3><%= link_to follow.username, user_path(follow), {:style=>'color:#110022;'} %></h3>
                    </div>
                    <div class="panel-body panelbodylead">
            	            <b>Email Address :</b>
                            <%= follow.email %><br>
                            <b>Location : </b>
                            <%= follow.location %>
                    </div>
                </div>
            </div>   
        <% end %>
    </div> 
</div>

app/views/home/index.html.erb
<div class="col-lg-12 text-center v-center">
    <%= render :partial => "/shared/search" %>
<%= will_paginate @user %>
    <div class="container"><hr>
        <div class="row">
            <% @user.each do |user| %>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading"><h3><%= link_to user.username, user_path(user), {:style=>'color:#110022;'} %></h3>
                        </div>
                        <div class="panel-body panelbodylead">
            	            <b>Email Address :</b>
                            <%= user.email %><br>
                            <b>Location : </b>
                            <%= user.location %>
                        </div>
                    </div>
                </div>   
            <% end %>
        </div> 
    </div> 
<%= will_paginate @user %>
</div>



  

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
  	<center>
    <p class="text-muted credit">Mini Fb</p>
    </center>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="wrap">
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Mini Facebook</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Edit", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", logout_path, method: :delete  %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", login_path %></li>
            <li><%= link_to "Sign in with facebook", "/auth/facebook" %></li>
            <li><%= link_to "Sign up", register_path %></li>
          <% end %>
        </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<title>
      MiniFb
    </title>
  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  		<%= csrf_meta_tags %>
	</head>
	<body>
    <!-- Wrap all page content here -->
  	<%= render 'layouts/header' %>
    <div class="container-full">
      <div class="row">
        <div class="col-lg-12 v-center">
          <p class="notice lead"><%= notice %></p>
          <p class="alert lead"><%= alert %></p>
          <%= yield %>
        </div>
      </div> <!-- /row -->
    </div> <!-- /container full -->
    <%= render 'layouts/footer' %>
	</body>
</html>

app/views/shared/_friend.html.erb
<h2 class="lead"><%= @user.username %>'s Friend List </h2><hr>
<div class="container">
  <div class="row">
  <% @user.user_followers.each do |follower| %>
      <% @user.following_users.each do |following| %>
       <% if follower == following %>
      <div class="col-md-4">
            <div class="panel panel-default">
               <div class="panel-heading"><h3><%= link_to follower.username, user_path(follower), {:style=>'color:#110022;'} %></h3></div>
               <div class="panel-body panelbodylead">
                <b>Email Address :</b><%= follower.email %><br>
                <b>Location : </b><%= follower.location %>
              </div>
            </div>
          </div>
           <% end %>
         <% end %>
        <% end %>
      </div>   
      </div> 
  </div> 

app/views/shared/_profile_pic.html.erb
<% if user_signed_in? %>
	<% if @user.oauth_token == nil %>
		<% if @user.photo.exists? %>
			<%= image_tag @user.photo.url(:small) %>
		<% else %>
			<%= image_tag "GenericProfile.png", :size => "150x150" %>
		<% end %>
	<% else %>
		<%= image_tag "http://graph.facebook.com/#{@user.uid}/picture?type=large" %>
	<% end %>
<% end %>

app/views/shared/_search.html.erb
<h1>Search User</h1>
<%= form_tag root_path, :method => 'get' do %>
          
        <div class="input-group" style="width:340px;margin:0 auto;">
             <table>
             	<tr>
                    <td> <%= text_field_tag :search, params[:search], :autofocus => true, :class => "form-control input-lg", :placeholder => "Enter Username here" %>
                    </td>
             	<td>
             		<div>
             			<%= submit_tag "Search", :username => nil, :class => "btn btn-lg btn-primary" %>
             		</div>
             	</td>
             </tr>
        	</table>
        </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<td>
<h1 class="lead">
<%= link_to "#{@user.follow_count} Following", user_follow_path(@user.id, @user.id, :info => "following"), {:style=>'color:#DDCCEE;'} %>
</h1>
</td>
<td>
<h1 class="lead">
<%= link_to "#{@user.followers_count} Followers", user_follow_path(@user.id, @user.id, :info => "followers"), {:style=>'color:#DDCCEE;'} %>
</h1>
</td>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
	<% if current_user.following?(@user) %>
		<div class="input-group" style="width:340px;margin:0 auto;">
    		<%= link_to "Unfollow", user_follow_path(@user.id, @user.id), :method => :delete, :class => "btn btn-lg btn-primary" %>
		</div>
	<% else %>
		<div class="input-group" style="width:340px;margin:0 auto;">
    		<%= link_to "Follow", user_follow_index_path(@user.id), :method => :post, :class => "btn btn-lg btn-primary" %>
		</div>
	<% end %>
<% end %>

app/views/users/show.html.erb
<div class="col-lg-12 text-center v-center">
	<%= render 'shared/profile_pic' %>
	<h1>
	<%= @user.username %>'s Profile
	</h1>
	<hr>
	<center>
	<table>
	<tr><td class="lead">Name : </td><td><%= @user.username %></td></tr>
	<tr><td class="lead">Location : </td><td><%= @user.location %></td></tr>
	<tr><td class="lead">email : </td><td><%= @user.email %></td></tr>
	<tr><%= render 'shared/stats' %></tr>
	</table>
	<% if user_signed_in? %>
		<div class="lead">
			<%= link_to "Albums", user_albums_path(@user.id), {:style=>'color:#DDCCEE;' } %>
			<%= render 'follow_form' %>
			<%= render 'shared/friend' %>
		</div>
	<% end %>
	</center>
</div>